
from enum import Enum

class AutomationState(Enum):
    QUEUED = "QUEUED"
    CLAIMED = "CLAIMED"
    PROFILE_STARTING = "PROFILE_STARTING"
    CDP_CONNECTING = "CDP_CONNECTING"
    PAGE_LOADING = "PAGE_LOADING"
    LOGIN_CHECK = "LOGIN_CHECK"
    READY = "READY"
    COMPOSER_OPEN = "COMPOSER_OPEN"
    CONTENT_ENTERED = "CONTENT_ENTERED"
    MEDIA_UPLOADED = "MEDIA_UPLOADED"
    VISIBILITY_SET = "VISIBILITY_SET"
    SUBMITTING = "SUBMITTING"
    VERIFYING = "VERIFYING"
    SUCCESS = "SUCCESS"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    STOPPED = "STOPPED"

    def __str__(self):
        return self.value

